fix: Actually abort if application disabled

diff --git a/bin/pojdectl-ng b/bin/pojdectl-ng
--- a/bin/pojdectl-ng
+++ b/bin/pojdectl-ng
@@ -2,8 +2,8 @@
 
 # Prefix for all objects in the Docker daemon.
 DOCKER_PREFIX=pojde-ng-
-# Scripts to run to apply/refresh instances. Order matters.
-SCRIPTS="parameters user apt code-server ttyd novnc jupyter-lab nginx docker ssh git modules webwormhole clean"
+# Scripts to run to apply/refresh instances. Order matters. "parameters" is run before all others.
+SCRIPTS="user apt code-server ttyd novnc jupyter-lab nginx docker ssh git modules webwormhole clean"
 # Prefix to display before destructive operations.
 CONFIRMATION_PREFIX="This could lead to data loss. Really"
 
@@ -186,6 +186,16 @@ apply)
     # If the container does already exist, start it
     else
         docker start ${DOCKER_PREFIX}${name}
+    fi
+
+    # Ask for parameters
+    docker exec -it ${docker_flags} ${DOCKER_PREFIX}${name} bash -c "/opt/pojde-ng/configuration/parameters.sh"
+
+    # Exit if aborted
+    if [ "$?" != "0" ]; then
+        echo "Apply aborted, exiting."
+
+        exit 1
     fi
 
     # Run the upgrade hooks of the scripts
